
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.34.0
    restart: on-failure:0
    ports:
    - 8081:8080
    - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      # AUTOSCHEMA_ENABLED: 'false'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      CLUSTER_HOSTNAME: 'node1'
      TRANSFORMERS_INFERENCE_API: http://text2vec-transformers:8080
  text2vec-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
      # NVIDIA_VISIBLE_DEVICES: all # enable if running with CUDA
  
  # reranker-transformers:  # Set the name of the inference container
  #   image: cr.weaviate.io/semitechnologies/reranker-transformers:cross-encoder-ms-marco-MiniLM-L-6-v2
  #   environment:
  #     ENABLE_CUDA: 0